#!/bin/bash
LOCAL_DIR=$1
RECV_HOST=$2
RECV_DIR=$3
MODE=$4
#echo "ls -1 $LOCAL_DIR | xargs -I {} -P 5 -n 1 rsync -avh --progress $LOCAL_DIR/{} $RECV_DIR"

if [ "$MODE" == "init" ];then
    rsync -a -f "+ */" -f "- *" $LOCAL_DIR $RECV_HOST:$RECV_DIR
    echo "rsync -a -f "+ */" -f "- *" $LOCAL_DIR $RECV_HOST:$RECV_DIR"
elif [ "$MODE" == "sync" ];then
    rsync -av -f "- /*/*/" $LOCAL_DIR/ $RECV_HOST:$RECV_DIR$LOCAL_DIR
    echo "rsync -a -f "- /*/*/" $LOCAL_DIR/ $RECV_HOST:$RECV_DIR$LOCAL_DIR"
fi
